version: '3.1'

services:

  web-server:
    image: jlennon91/php:1.0.9
    restart: always
    ports:
      - 8888:80
    volumes:
      - .:/var/www/html/app
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  composer:
    image: composer:latest
    command: 'true'
    volumes:
      - .:/app